license="MIT"
modLoader="javafml"
loaderVersion="[36,37)"
issueTrackerURL="https://github.com/Harleyoc1/DynamicTreesNaturesAura/issues"

[[mods]]
modId="dtnaturesaura"
version="${file.jarVersion}"
displayName="Dynamic Trees for Nature's Aura"
updateJSONURL="https://github.com/Harleyoc1/DynamicTreesNaturesAura/blob/1.16.5/version_info.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-natures-aura"
logoFile="dtna-logo.png"
credits=""
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility to Nature's Aura.
'''

[[dependencies.dtnaturesaura]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtnaturesaura]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtnaturesaura]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0-Beta27,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtnaturesaura]]
    modId="naturesaura"
    mandatory=true
    versionRange="[34.2,)"
    ordering="AFTER"
    side="BOTH"