license="MIT"
modLoader="javafml"
loaderVersion="[43,44)"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-NaturesAura/issues"

[[mods]]
modId="dtnaturesaura"
version="${file.jarVersion}"
displayName="Dynamic Trees for Nature's Aura"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/NaturesAura.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-natures-aura"
logoFile="dtna-logo.png"
credits=""
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility to Nature's Aura.
'''

[[dependencies.dtnaturesaura]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,44)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtnaturesaura]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtnaturesaura]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.1.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtnaturesaura]]
    modId="naturesaura"
    mandatory=true
    versionRange="[38.0,)"
    ordering="AFTER"
    side="BOTH"