@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.harleyoconnor.dtnaturesaura.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;